### ISSUE TITLE
The role of label_margin

### ISSUE THREAD

**Issue by egginsect** [nicolov/segmentation_keras#9]
Hi,

I am trying to fine-tune the segmentation model. 
I'd like to modify utils/image_reader.py to make it fit to the network with input 900x900 since it's 500x500 now in image_reader.py. 
I am confused with the role of label_margin. How do I determine the value of label_margin?
Thanks.

Hao-Wei

**Comment by nicolov** [comment]
In the original code, the network only predicts the segmentation for the center area of the image, and `label_margin` pixels are ignored on each side. I believe that the idea behind this was to have some "context" to improve results.

In practical terms, this means that we have to pad the original image with `label_margin` pixels to make sure that the first pixel in the predicted segmentation matches the first pixel in the ground truth.

If you're using the code for a new task, you don't need to follow the same pre-processing steps. I just re-implemented the original paper so that I could compare results.
